In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.utils import to_categorical

# 加载 CIFAR-10 数据集
(X_train, y_train), (X_test, y_test) = cifar10.load_data()
print(X_train)

# 数据预处理
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0
print(X_train)

# 将标签转换为 one-hot 编码
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# 构建卷积神经网络模型
model = Sequential([
    # 卷积层，使用 32 个 3x3 的卷积核，激活函数为 ReLU。输入形状为 (32, 32, 3)，表示 32x32 的彩色图像。提取低级特征（如边缘、纹理）。
    # 卷积核的数量（即卷积层的深度）是一个超参数，通常通过实验和经验来选择。使用 32 个卷积核是一个常见的选择，特别是在处理 CIFAR-10 这样相对较小和简单的数据集时。这一选择背后的原因包括以下几点：
    # 1. 特征提取的能力
    #  - 使用 32 个卷积核可以在一定程度上捕捉到输入图像中的多种特征。每个卷积核都可以学习到不同的特征表示，例如边缘、纹理、颜色等。通过增加卷积核的数量，可以提取更丰富的特征。
    # 2. 计算成本和内存限制
    #  - 卷积核的数量直接影响到模型的参数量和计算成本。对于较浅的网络（如包含 3 个卷积层的简单 CNN），32 个卷积核可以提供足够的特征提取能力，同时不会过度增加计算量和内存需求。在较深的网络中，卷积核的数量通常会逐层增加。
    # 3. 经验和实践
    #  - 在许多经典的 CNN 架构中，如 LeNet、AlexNet 等，较浅层的卷积层通常会使用相对较少的卷积核（如 32、64 个），而较深层的卷积层则会使用更多的卷积核（如 128、256 个）。这种设计是基于大量实践和实验验证的结果。
    Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    # 使用 2x2 的池化窗口。MaxPooling2D 是卷积神经网络（CNN）中的一种池化层，用于对输入特征图进行下采样（或降采样），从而减少特征图的尺寸并保留重要特征。这对于减少计算复杂度和防止过拟合非常有用。
    MaxPooling2D((2, 2)),
    # 第二个卷积层，使用 64 个 3x3 的卷积核，激活函数为 ReLU。提取中级特征（如角点、简单形状）。
    Conv2D(64, (3, 3), activation='relu'),
    # 第二个池化层，使用 2x2 的池化窗口。
    MaxPooling2D((2, 2)),
    # 第三个卷积层，使用 128 个 3x3 的卷积核，激活函数为 ReLU。提取高级特征（如物体的一部分、复杂结构）。
    Conv2D(128, (3, 3), activation='relu'),
    # 展平层，将多维输入展平为一维。
    Flatten(),
    # 全连接层，128 个神经元，激活函数为 ReLU。
    Dense(128, activation='relu'),
    # 丢弃层，防止过拟合，丢弃率为 0.5。
    Dropout(0.5),
    # 输出层，10 个神经元，激活函数为 Softmax，用于多分类任务。
    Dense(10, activation='softmax')
])

# 编译模型
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# 训练模型
history = model.fit(X_train, y_train, epochs=20, batch_size=64, validation_split=0.2)

# 评估模型
test_loss, test_acc = model.evaluate(X_test, y_test)
print("Test accuracy:", test_acc)


[[[[ 59  62  63]
   [ 43  46  45]
   [ 50  48  43]
   ...
   [158 132 108]
   [152 125 102]
   [148 124 103]]

  [[ 16  20  20]
   [  0   0   0]
   [ 18   8   0]
   ...
   [123  88  55]
   [119  83  50]
   [122  87  57]]

  [[ 25  24  21]
   [ 16   7   0]
   [ 49  27   8]
   ...
   [118  84  50]
   [120  84  50]
   [109  73  42]]

  ...

  [[208 170  96]
   [201 153  34]
   [198 161  26]
   ...
   [160 133  70]
   [ 56  31   7]
   [ 53  34  20]]

  [[180 139  96]
   [173 123  42]
   [186 144  30]
   ...
   [184 148  94]
   [ 97  62  34]
   [ 83  53  34]]

  [[177 144 116]
   [168 129  94]
   [179 142  87]
   ...
   [216 184 140]
   [151 118  84]
   [123  92  72]]]


 [[[154 177 187]
   [126 137 136]
   [105 104  95]
   ...
   [ 91  95  71]
   [ 87  90  71]
   [ 79  81  70]]

  [[140 160 169]
   [145 153 154]
   [125 125 118]
   ...
   [ 96  99  78]
   [ 77  80  62]
   [ 71  73  61]]

  [[140 155 164]
   [139 146 149]
   [115 115 112]
   ...
   [ 79  82  64]
   [ 68  70  55]
   [ 67  69

SyntaxError: 'return' outside function (3369848542.py, line 16)