In [13]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# 加载MNIST数据集
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
print(len(train_images)) # 60000
# 预处理数据
# 在数据预处理中，.astype('float32') / 255 是一种常见的操作，特别是在处理图像数据时。这个操作的目的是将图像数据进行归一化，使得像素值从原始的 0-255 范围缩放到 0-1 范围。
# (60000, 28, 28)：图像数据没有显式的通道维度。这种形状适用于一些简单的模型，但对于卷积神经网络（CNN），不太合适。
# (60000, 28, 28, 1)：图像数据包含显式的通道维度（灰度图像的通道数为 1）。这种形状对于卷积神经网络（CNN）非常重要，因为卷积操作需要通道维度的信息
train_images = train_images.reshape((60000, 28, 28, 1)).astype('float32') / 255
test_images = test_images.reshape((10000, 28, 28, 1)).astype('float32') / 255

# to_categorical用于将整数标签转换为 one-hot 编码。这在分类任务中特别有用，因为许多机器学习模型更容易处理 one-hot 编码的标签。
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

# 创建Sequential模型
model = Sequential()

# 添加Flatten层，将输入的28x28图像展平为一维向量
# 为什么需要`Flatten`？
# - 在卷积神经网络（CNN）中，卷积层和池化层的输出通常是多维的张量（例如 3D 的高度、宽度、通道）。然而，全连接层（Dense 层）需要一维的输入。因此，在将卷积层或池化层的输出传递给全连接层之前，需要使用 Flatten 层将其展平。
model.add(Flatten(input_shape=(28, 28, 1)))

# 添加一个具有128个神经元的全连接层，激活函数为ReLU
# 为什么选择128个神经元？
# - 经验法则：在许多任务中，128个神经元的Dense层被证明是一个合理的起点。它足够大，可以捕捉到复杂的模式，同时计算开销不至于过高。
# - 容量和表现力：增加神经元数量可以增加模型的容量和表现力，使其能够学习和拟合更复杂的函数关系。但过多的神经元也可能导致过拟合（overfitting）
# - 计算资源：更多的神经元需要更多的计算资源和更长的训练时间。128个神经元在许多任务中能提供良好的表现，而不会显著增加计算负担。
model.add(Dense(128, activation='relu'))

# 添加输出层，使用softmax激活函数进行多分类
model.add(Dense(10, activation='softmax'))

# 编译模型，指定损失函数、优化器和评估指标
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# 训练模型
# 在训练神经网络时，epochs 是一个重要的参数，用于指定训练过程中数据集被完整迭代的次数。每次完整的迭代称为一个 epoch。以下是关于 epochs 参数及其作用的详细解释。
# 什么是 Epoch
#  - Epoch：一个 epoch 表示对整个训练数据集进行一次完整的遍历。
#  - Batch：在一个 epoch 中，数据通常被分成多个小批量（batches）进行训练。每个 batch 包含若干样本。
#  - Iteration：一个 epoch 中包含的迭代次数等于训练集样本总数除以批量大小。例如，如果有 1000 个样本，每个 batch 大小为 100，那么每个 epoch 将包含 10 次迭代。
model.fit(train_images, train_labels, epochs=5, batch_size=32, validation_split=0.1)

# 评估模型
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"Test accuracy: {test_acc}")


60000
[5 0 4 ... 5 6 8]
train_labels [[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
Epoch 1/5


/Users/huke/openai-learning/venv2405/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 821us/step - accuracy: 0.8771 - loss: 0.4448 - val_accuracy: 0.9622 - val_loss: 0.1301
Epoch 2/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 755us/step - accuracy: 0.9630 - loss: 0.1288 - val_accuracy: 0.9728 - val_loss: 0.1003
Epoch 3/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 736us/step - accuracy: 0.9766 - loss: 0.0812 - val_accuracy: 0.9712 - val_loss: 0.0992
Epoch 4/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 730us/step - accuracy: 0.9810 - loss: 0.0649 - val_accuracy: 0.9747 - val_loss: 0.0870
Epoch 5/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 738us/step - accuracy: 0.9866 - loss: 0.0457 - val_accuracy: 0.9752 - val_loss: 0.0884
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 297us/step - accuracy: 0.9686 - loss: 0.0973
Test accuracy: 0.9732000231742859
